# Site settings
title: Matt Stasch
#email: contact@mattstasch.net
email: matt.stasch@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Programming, hacking, maybe hardware... basically stuff! :D
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattstasch.net" # the base hostname & protocol for your site
twitter_username: mattstasch
github_username:  mat3u

# Build settings
markdown: kramdown
highlighter: true

# Permalinks
permalink: pretty

paginate: 5

# External systems
tracking_id: "UA-58896348-1"
#disqus_id: ""

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Matt Stasch"
      layout: "post"
      comments: true
