# Site settings
title: Matt Stasch
email: matt.stasch@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Programming, hacking, maybe hardware... basically stuff! :D
baseurl: ""
url: "http://mattstasch.net"
twitter_username: mattstasch
github_username:  mat3u

# Build settings
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: /:year/:month/:title

paginate: 5

# External systems
tracking_id: "UA-58896348-1"
hostname: "mattstasch.net"
disqus_id: "mattstasch"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Matt Stasch"
      layout: "post"
      comments: true
